//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBase_ASP_DOT_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlbumTable()
        {
            this.AlbumHasArtists = new HashSet<AlbumHasArtists>();
            this.AlbumHasTracks = new HashSet<AlbumHasTracks>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Href { get; set; }
        public string ImageURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumHasArtists> AlbumHasArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumHasTracks> AlbumHasTracks { get; set; }
    }
}
