//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBase_ASP_DOT_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArtistTable()
        {
            this.AlbumHasArtists = new HashSet<AlbumHasArtists>();
            this.TrackTable = new HashSet<TrackTable>();
            this.TrackHasArtists = new HashSet<TrackHasArtists>();
            this.TracksHasArtist = new HashSet<TracksHasArtist>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Href { get; set; }
        public string Genre { get; set; }
        public Nullable<long> FollowersTotal { get; set; }
        public Nullable<long> Popularity { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumHasArtists> AlbumHasArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackTable> TrackTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackHasArtists> TrackHasArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TracksHasArtist> TracksHasArtist { get; set; }
    }
}
