//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBase_ASP_DOT_NET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iBaseEntities : DbContext
    {
        public iBaseEntities()
            : base("name=iBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AlbumHasArtists> AlbumHasArtists { get; set; }
        public virtual DbSet<AlbumHasTracks> AlbumHasTracks { get; set; }
        public virtual DbSet<AlbumTable> AlbumTable { get; set; }
        public virtual DbSet<ArtistTable> ArtistTable { get; set; }
        public virtual DbSet<PlaylistHasTracks> PlaylistHasTracks { get; set; }
        public virtual DbSet<PlaylistTable> PlaylistTable { get; set; }
        public virtual DbSet<TrackHasArtists> TrackHasArtists { get; set; }
        public virtual DbSet<TracksHasArtist> TracksHasArtist { get; set; }
        public virtual DbSet<TrackTable> TrackTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
