//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBase_ASP_DOT_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistHasTracks
    {
        public int Id { get; set; }
        public string TrackId { get; set; }
        public Nullable<int> PlaylistId { get; set; }
    
        public virtual PlaylistTable PlaylistTable { get; set; }
        public virtual TrackTable TrackTable { get; set; }
    }
}
