//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBase_ASP_DOT_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaylistTable()
        {
            this.PlaylistHasTracks2 = new HashSet<PlaylistHasTracks>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> PlaylistHasTracks { get; set; }
    
        public virtual PlaylistHasTracks PlaylistHasTracks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistHasTracks> PlaylistHasTracks2 { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
