//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBase_ASP_DOT_NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrackTable()
        {
            this.AlbumHasTracks = new HashSet<AlbumHasTracks>();
            this.PlaylistHasTracks = new HashSet<PlaylistHasTracks>();
            this.TrackHasArtists = new HashSet<TrackHasArtists>();
            this.TracksHasArtist = new HashSet<TracksHasArtist>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Album { get; set; }
        public Nullable<int> DiscNumber { get; set; }
        public Nullable<long> DurationMS { get; set; }
        public Nullable<bool> Explicity { get; set; }
        public string Href { get; set; }
        public Nullable<long> Popularity { get; set; }
        public string ImageURL { get; set; }
        public string PreviewURL { get; set; }
        public Nullable<int> TrackNumber { get; set; }
        public string Type { get; set; }
        public string ArtistID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumHasTracks> AlbumHasTracks { get; set; }
        public virtual ArtistTable ArtistTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistHasTracks> PlaylistHasTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackHasArtists> TrackHasArtists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TracksHasArtist> TracksHasArtist { get; set; }
    }
}
